[package]
authors = ["Twilight Contributors"]
edition = "2018"
name = "twilight-http-proxy"
version = "0.1.0"

[dependencies]
twilight-http = { branch = "trunk", git = "https://github.com/twilight-rs/twilight.git" }
hyper = "0.13"
http = "0.2"
log = "0.4"
pretty_env_logger = "0.3"
reqwest = "0.10"
snafu = "0.5"
tokio = { version = "0.2", features = ["macros"] }
